### ISSUE TITLE
Broken Scripts

### ISSUE THREAD

**Issue by fruzitent** [microsoft/containers-toolkit#4]
**Describe the bug**
`Install-BuildKit` attempts to untar files into directory with the name of the tarball itself.
`Install-ContainerTools` is unable to find `downloadfile` macro.

**To Reproduce**
1. `Import-Module -Name "./ContainerToolsForWindows" -Force`
2. `Install-Buildkit`
3. `Install-ContainerTools`

**Expected behavior**
Installation to be successful.

**Screenshots**
![kegIgcE04Q](https://github.com/microsoft/containers-toolkit/assets/40008647/f3890410-bb05-46f6-a60e-e569bf80f645)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Additional context**

**Comment by TinaMor** [comment]
@fruzitent We are working on implementing the `-whatif` parameter and updating documents on each command.

References:

[PowerShell Basics: Don't Fear Hitting Enter with -WhatIf](https://techcommunity.microsoft.com/t5/itops-talk-blog/powershell-basics-don-t-fear-hitting-enter-with-whatif/ba-p/353579)
